<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="p20_timer" Id="{5e4b95fb-c4c9-4cab-ab38-cbb69043119d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM p20_timer
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="p20_timer">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>